name: assignment-test
on:
    push:
        tags-ignore:
            - '*'
        branches:
            - '*'
jobs:
    full-test:
        runs-on: self-hosted
        steps:
          - name: Simulate Success
            run: echo "Full test simulated success"
